# Generated by Django 5.2.7 on 2025-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='last_price',
        ),
        migrations.AddField(
            model_name='card',
            name='price_at_addition',
            field=models.FloatField(default=0),
        ),
    ]
